# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiaAlerts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fia Alerts
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'Alamofire'
  pod 'SnapKit'

end
